-- This is run line by line, so avoid multiline queries syntax and no ; at end
INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('John Doe', 'johndoe@example.com', 'password')
INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('Jane Doe', 'janedoe@example.com', 'password')
INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('John Smith', 'johnsmith@example.com', 'password')

-- these are used for system testing, don't use them or their ids (4, 5) unless altering system tests
INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('admin_test_user1', 'admin_test_user1@myumanitoba.com', 'password')
INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('admin_test_user2', 'admin_test_user2@example.com', 'password')

INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('James Smith', 'jamesSmith@example.com', 'password')
INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('Johnny Test', 'johnnyTest@example.com', 'password')
INSERT INTO PUBLIC.USERS (USERNAME, EMAIL, PASSWORD) VALUES ('Jon Jest', 'jonJest@example.com', 'password')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Open AI', 'An introduction to Open AI')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Cloud Computing', 'An introduction to cloud computing')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Calculus', 'An introduction to calculus')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Psychology', 'An introduction to psychology')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Cool Pens', '10 pens of varying colors')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Used Chromebook', 'A used Chromebook 2016')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Principles of Quantum Mechanics', '4th year physics textbook')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Art Canvas', 'Painting canvas for art students')
INSERT INTO PUBLIC.PRODUCTS (NAME, DESCRIPTION) VALUES ('Programing Pearls', 'Introduction to C language')
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, EXPIRY, MINBID) VALUES (5, 7, 'Principles of Quantum Mechanics', 'Phy textbook', 'images/Quantum.jpg', DateAdd('day', 1, CURRENT_DATE), 20)
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, EXPIRY, MINBID) VALUES (1, 1, 'Open AI', 'An introduction to Open AI', 'images/AI.jpg', DateAdd('day', 5, CURRENT_DATE), 20.0)
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, EXPIRY, MINBID) VALUES (1, 4, 'Psychology', 'An introduction to psychology', 'images/Psychology.jpg', DateAdd('day', 5, CURRENT_DATE), 25.0)
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, EXPIRY, MINBID) VALUES (2, 2, 'Cloud Computing', 'An introduction to cloud computing', 'images/Cloud Computing.jpg', DateAdd('day', 5, CURRENT_DATE), 20.0)
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, EXPIRY, MINBID) VALUES (3, 3, 'Calculus', 'An introduction to calculus', 'images/Calculus.jpg', DateAdd('day', 5, CURRENT_DATE), 25.0)
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, MINBID, EXPIRY, DATECREATED) VALUES (1, 5, 'Selling pens', 'Selling 10 pens of varying colors', 'images/Pens.jpg', 12, DateAdd('day', 3, CURRENT_DATE), DateAdd('day', -1, CURRENT_DATE))
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, MINBID, EXPIRY, DATECREATED) VALUES (1, 6, 'Selling Used Chromebook', 'Chromebook is from 2016, used for 2 years.', 'images/Chromebook.webp', 12, DateAdd('day', -2, CURRENT_DATE), DateAdd('day', -5, CURRENT_DATE))
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, EXPIRY, MINBID) VALUES (5, 8, 'Canvas', 'Painting canvas for art students', 'images/Painting.jpg', DateAdd('day', 30, CURRENT_DATE), 25.0)
INSERT INTO PUBLIC.AUCTIONS (SELLERID, PRODUCTID, TITLE, DESCRIPTION, IMAGEPATH, EXPIRY, MINBID) VALUES (5, 9, 'Programing Pearls', 'Introduction to C', 'images/Programming.jpg', DateAdd('day', 31, CURRENT_DATE), 25.0)
INSERT INTO PUBLIC.BIDS (AUCTIONID,USERID,PRICE,STATUS) VALUES (2, 2, 21, 'Bid Ongoing')
INSERT INTO PUBLIC.BIDS (AUCTIONID,USERID,PRICE,STATUS) VALUES (2, 3, 50, 'Bid Ongoing')
INSERT INTO PUBLIC.BIDS (AUCTIONID,USERID,PRICE,STATUS) VALUES (2, 5, 51, 'Bid Ongoing')
INSERT INTO PUBLIC.BIDS (AUCTIONID,USERID,PRICE,STATUS) VALUES (2, 6, 60, 'Bid Ongoing')
INSERT INTO PUBLIC.BIDS (AUCTIONID,USERID,PRICE,STATUS) VALUES (3, 2, 25, 'Bid Ongoing')
INSERT INTO PUBLIC.BIDS (AUCTIONID,USERID,PRICE,STATUS) VALUES (3, 3, 31, 'Bid Ongoing')